version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - media-app

networks:
  media-app:
    name: media-app
    external: true
