version: "3.8"
services:
  postgres:
    image: postgis/postgis
    container_name: 'postgres'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      LANG: "C"
      LC_CTYPE: "C"
      LC_COLLATE: "C"
    volumes:
      - ./psql-ext.sql:/docker-entrypoint-initdb.d/psql_ext.sql
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - media-services

  s3:
    image: scality/s3server:latest
    container_name: 's3server'
    ports:
      - "8000:8000"
    volumes:
      - s3data:/usr/src/app/var/data
      - ./config.json:/usr/src/app/config.json
    environment:
      - S3DATADIR=/usr/src/app/var/data
    networks:
      media-services:
        ipv4_address: 172.16.238.10
networks:
  media-services:
    name: media-services
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
volumes:
  s3data:
