version: "3"
services:
  postgres:
    image: postgis/postgis
    container_name: 'postgressql-media'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      LANG: "C"
      LC_CTYPE: "C"
      LC_COLLATE: "C"
    volumes:
      - ./psql-ext.sql:/docker-entrypoint-initdb.d/psql_ext.sql
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready -U test' ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6.2-alpine
    container_name: 'redis6'
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass test --loglevel warning
  s3:
    image: scality/s3server:latest
    container_name: 's3server'
    ports:
      - 8000:8000
