version: "3.9"
services:
  postgres:
    image: postgis/postgis
    container_name: 'postgres'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      LANG: "C"
      LC_CTYPE: "C"
      LC_COLLATE: "C"
    volumes:
      - ./psql-ext.sql:/docker-entrypoint-initdb.d/psql_ext.sql
      - .:/var/lib/postgresql/data
    restart: unless-stopped

  s3:
    image: scality/s3server:latest
    container_name: 's3server'
    volumes:
      - s3data:/usr/src/app/var/data
      - ./config.json:/usr/src/app/config.json
    environment:
      - S3DATADIR=/usr/src/app/var/data
volumes:
  s3data:
