livenessProbe:
  path: "/health"
readinessProbe:
  path: "/health"
service:
  externalPort: 3000
  internalPort: 3000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    #nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/server-snippet: |-
       more_set_headers "Access-Control-Allow-Origin: $http_origin";
       more_set_headers "Access-Control-Allow-Credentials: true";
       more_set_headers "Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS";
       more_set_headers "Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Fdi-Version,RID,Anti-csrf";
#      location /metrics {
#          deny all;
#      }
